architect:
  - ardesco
docker:
  image: "velo/rultor8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.kbx.asc"
env:
 JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
release:
  pre: false
  script: |-
    mkdir /home/r/gpg
    mv /home/r/pubring.kbx /home/r/gpg/pubring.kbx
    sudo chmod -R 700 /home/r/gpg
    mvn versions:set "-DnewVersion=${tag}"
    export PATH=$JAVA_HOME/bin:$PATH
    set
    javac -version
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings /home/r/settings.xml
  commanders:
  - ardesco
